🌿 Add Ruby model generation + upgrade the Fern generator
AssemblyAI/assemblyai-api-spec pull request #44
Opened 2024-01-24 00:30 UTC by armandobelardo

2024-01-24 02:23 UTC, Swimburger commented on fern/generators.yml
> +          gemName: assemblyai_ruby
This looks like it is under the wrong publish group.
The PR that @dsinghvi made for C# creates its own publish group: https://github.com/AssemblyAI/assemblyai-api-spec/pull/41

2024-01-24 02:23 UTC, Swimburger commented
I can make the repo public

2024-01-24 14:03 UTC, armandobelardo commented on fern/generators.yml
> +          gemName: assemblyai_ruby
Great catch @Swimburger, updated to per-generator groups!

2024-01-24 15:52 UTC, Swimburger commented
We can keep it private for now, but as long as we communicate that it isn't ready, it wouldn't be a problem for it to be public either.

2024-01-24 15:52 UTC, Swimburger commented
LGTM! @dsinghvi will the CI work with these changes?

2024-01-25 20:00 UTC, Swimburger requested changes

2024-01-25 20:00 UTC, Swimburger commented on fern/generators.yml
> +          gemName: assemblyai_ruby
Can we name the gem `assemblyai` instead of `assemblyai-ruby`.

2024-01-25 20:06 UTC, armandobelardo commented on fern/generators.yml
> +          gemName: assemblyai_ruby
Yes definitely, will go ahead and update!

2024-01-25 21:51 UTC, Swimburger approved these changes

2024-01-26 19:32 UTC, dsinghvi commented
> LGTM! @dsinghvi will the CI work with these changes?

Will follow up with the CI changes!

2024-01-26 19:32 UTC, merged